#!/usr/bin/env node
/**
 * check-before 的文件屬性、xlsx 讀取、客戶來信對照（--thread）、合約條款比對（--prev）測試。
 * 測試檔由 Python 標準函式庫 zipfile 現做（不需 python-pptx／openpyxl），pdf 用 PyMuPDF 現做。
 * 產生工具預設值用的是實際讀出來的值（PptxGenJS 4.0.1、python-pptx 1.0.2、python-docx 1.2.0、openpyxl 3.1.5），
 * 見 references/banned-patterns.json 的 generator_defaults。
 * 用法：node hooks/tests/metadata-and-compare.test.js
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..', '..');
const core = require(path.join(ROOT, 'hooks', 'lib', 'readability-scan.core.js'));
const CHECK = path.join(ROOT, 'skills', 'check-before', 'scripts', 'check_doc.js');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'dr-meta-'));
let pass = 0, fail = 0;
function t(label, ok, detail) {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok ? '' : '  → ' + detail}`);
  ok ? pass++ : fail++;
}
function py(code, ...args) {
  for (const exe of ['python', 'python3', 'py']) {
    const r = spawnSync(exe, ['-c', code, ...args], { encoding: 'utf8' });
    if (r.error && r.error.code === 'ENOENT') continue;
    if (r.status !== 0) throw new Error(r.stderr);
    return r.stdout;
  }
  throw new Error('找不到 python');
}
// files：{ entry: 內容 }，寫成 zip
function zip(file, files) {
  py(`
import sys, json, zipfile
with zipfile.ZipFile(sys.argv[2], 'w', zipfile.ZIP_DEFLATED) as z:
    for k, v in json.loads(sys.argv[1]).items(): z.writestr(k, v.encode('utf-8'))
`, JSON.stringify(files), file);
  return file;
}
function check(args) {
  const r = spawnSync(process.execPath, [CHECK, ...args], { encoding: 'utf8' });
  return { code: r.status, out: r.stdout + r.stderr };
}

const CORE = (fields) => '<?xml version="1.0"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" ' +
  'xmlns:dc="http://purl.org/dc/elements/1.1/">' + fields + '</cp:coreProperties>';
const APP = (fields) => '<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">' + fields + '</Properties>';
const DOC = (paras) => '<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' +
  paras.map((p) => `<w:p><w:r><w:t>${p}</w:t></w:r></w:p>`).join('') + '</w:body></w:document>';

// ---- 文件屬性：產生工具預設值（欄位＋值成對）----
const pgj = zip(path.join(tmp, 'pgj.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE('<dc:title>PptxGenJS Presentation</dc:title><dc:subject>PptxGenJS Presentation</dc:subject>' +
    '<dc:creator>PptxGenJS</dc:creator><cp:lastModifiedBy>PptxGenJS</cp:lastModifiedBy>'),
  'docProps/app.xml': APP('<Company>PptxGenJS</Company><Application>Microsoft Office PowerPoint</Application>'),
});
let m = core.checkMetadata(pgj);
t('PptxGenJS 預設的標題、主旨、作者、最後修改者、公司五欄都擋', m.bad.length === 5 && m.bad.every((b) => b.includes('PptxGenJS')), JSON.stringify(m.bad));
t('Application＝Microsoft Office PowerPoint 不擋（不實但不洩漏）', !m.bad.some((b) => b.includes('應用程式')), JSON.stringify(m.bad));

const canny = zip(path.join(tmp, 'canny.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE('<dc:title>交接說明</dc:title><dc:creator>Steve Canny</dc:creator><cp:lastModifiedBy>Steve Canny</cp:lastModifiedBy>'),
});
m = core.checkMetadata(canny);
t('Steve Canny 只在最後修改者欄算預設值，作者欄是人名不算', m.bad.length === 1 && m.bad[0].includes('最後修改者'), JSON.stringify(m.bad));

const pydocx = zip(path.join(tmp, 'pydocx.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE('<dc:creator>python-docx</dc:creator><dc:description>generated by python-docx</dc:description>'),
  'docProps/app.xml': APP('<Application>Microsoft Macintosh Word</Application>'),
});
m = core.checkMetadata(pydocx);
t('python-docx 範本的作者與描述都擋', m.bad.length === 2, JSON.stringify(m.bad));
t('沒有標題 → 提醒（不擋）', m.notes.some((n) => n.includes('沒有標題')), JSON.stringify(m.notes));

const xlDefault = zip(path.join(tmp, 'opx.xlsx'), {
  'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="工作表" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/worksheets/sheet1.xml': '<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>內容</t></is></c></row></sheetData></worksheet>',
  'docProps/core.xml': CORE('<dc:creator>openpyxl</dc:creator>'),
  'docProps/app.xml': APP('<Application>Microsoft Excel Compatible / Openpyxl 3.1.5</Application>'),
});
m = core.checkMetadata(xlDefault);
t('openpyxl 的作者與帶版號的應用程式（pattern 比對）都擋', m.bad.length === 2 && m.bad.some((b) => b.includes('Openpyxl 3.1.5')), JSON.stringify(m.bad));

const aiMeta = zip(path.join(tmp, 'ai.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE('<dc:title>系統說明</dc:title><dc:creator>Claude</dc:creator>'),
});
m = core.checkMetadata(aiMeta);
t('文件屬性含 AI 工具名稱 → 硬缺陷', m.bad.some((b) => b.includes('AI 工具名稱') && b.includes('Claude')), JSON.stringify(m.bad));

const clean = zip(path.join(tmp, '報價單.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE('<dc:title>報價單</dc:title><dc:creator>王小明</dc:creator>'),
  'docProps/app.xml': APP('<Company>範例資訊股份有限公司</Company>'),
});
m = core.checkMetadata(clean);
t('正常填寫的屬性 → 0 硬缺陷、0 提醒', m.bad.length === 0 && m.notes.length === 0, JSON.stringify(m));
const other = path.join(tmp, '交接說明.docx');
fs.copyFileSync(clean, other);
t('標題「報價單」、檔名「交接說明」→ 提醒可能是別份文件的標題', core.checkMetadata(other).notes.some((n) => n.includes('看不出關聯')), '');
const eng = path.join(tmp, 'quote-v2.docx');
fs.copyFileSync(clean, eng);
t('中文標題配英文檔名比不出來 → 不提醒', core.checkMetadata(eng).notes.length === 0, JSON.stringify(core.checkMetadata(eng).notes));
t('md 沒有文件屬性 → checkMetadata 回 null', core.checkMetadata(path.join(tmp, 'x.md')) === null, '');

// ---- PDF 文件屬性：Chrome 列印（to-checklist 自己的產出）不擋 ----
let havePdf = true;
const pdfChrome = path.join(tmp, 'chrome.pdf'), pdfPgj = path.join(tmp, 'pgj.pdf');
try {
  py(`
import sys, fitz
for f, meta in ((sys.argv[1], {'title': '確認清單', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/145.0.0.0 Safari/537.36', 'producer': 'Skia/PDF m145'}),
                (sys.argv[2], {'title': 'PptxGenJS Presentation', 'author': 'PptxGenJS', 'subject': 'PptxGenJS Presentation', 'producer': 'x', 'creator': 'x'})):
    d = fitz.open(); d.new_page().insert_text((72, 72), 'hello'); d.set_metadata(meta); d.save(f)
`, pdfChrome, pdfPgj);
} catch (e) { havePdf = false; console.log('SKIP  PDF 文件屬性（沒有 PyMuPDF）：' + String(e.message).split('\n').pop()); }
if (havePdf) {
  m = core.checkMetadata(pdfChrome);
  t('Chrome 列印的 PDF（HeadlessChrome／Skia/PDF）→ 0 硬缺陷', m.bad.length === 0, JSON.stringify(m.bad));
  m = core.checkMetadata(pdfPgj);
  t('PowerPoint 轉出的 PDF 帶著 PptxGenJS 預設的標題、作者、主旨 → 三項都擋', m.bad.length === 3, JSON.stringify(m.bad));
}

// ---- xlsx 讀取 ----
const xl = zip(path.join(tmp, '人天估算.xlsx'), {
  'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>' +
    '<sheet name="估算" sheetId="1" r:id="rId1"/><sheet name="內部試算" sheetId="2" state="hidden" r:id="rId2"/>' +
    '<sheet name="草稿" sheetId="3" state="veryHidden" r:id="rId3"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/>' +
    '<Relationship Id="rId2" Target="/xl/worksheets/sheet2.xml"/><Relationship Id="rId3" Target="worksheets/sheet3.xml"/></Relationships>',
  // 共用字串：第 1 筆有拼音標註（不是內容），第 2 筆是 rich text 分段
  'xl/sharedStrings.xml': '<sst><si><t>報表</t><rPh sb="0" eb="1"><t>ホウヒョウ</t></rPh></si><si><r><t>本次</t></r><r><rPr><b/></rPr><t>查核</t></r></si></sst>',
  'xl/worksheets/sheet1.xml': '<worksheet><cols><col min="1" max="1"/></cols><sheetData><row><c r="A1" t="s"><v>0</v></c><c r="B1"/>' +
    '<c r="C1" t="str"><f>A1</f><v>公式字串</v></c></row></sheetData></worksheet>',
  'xl/worksheets/sheet2.xml': '<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>成本 buffer 20%</t></is></c></row></sheetData></worksheet>',
  'xl/worksheets/sheet3.xml': '<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>本段由 Codex 產生</t></is></c></row></sheetData></worksheet>',
  'xl/comments1.xml': '<comments><commentList><comment ref="A1"><text><r><t>原價 15 人天</t></r></text></comment></commentList></comments>',
  'xl/comments/comment2.xml': '<comments><commentList><comment ref="B1"><text><t>比照去年</t></text></comment></commentList></comments>',
  'docProps/core.xml': CORE('<dc:title>人天估算</dc:title><dc:creator>王小明</dc:creator>'),
});
const x = core.readXlsx(xl);
t('三張工作表與狀態都讀到（Target 絕對路徑與相對路徑都認）',
  x && x.sheets.map((s) => s.name + ':' + s.state).join() === '估算:visible,內部試算:hidden,草稿:veryHidden', JSON.stringify(x && x.sheets));
t('共用字串去掉拼音標註、rich text 分段接起來', x && JSON.stringify(x.shared) === JSON.stringify(['報表', '本次查核']), JSON.stringify(x && x.shared));
t('同一列的共用字串與公式字串接成一行、內嵌字串也讀到', x && x.sheets[0].rows[0] === '報表　公式字串' && x.sheets[2].rows.includes('本段由 Codex 產生'), JSON.stringify(x && x.sheets));
t('沒被儲存格引用的共用字串另外收（不漏掃）', x && JSON.stringify(x.orphan) === JSON.stringify(['本次查核']), JSON.stringify(x && x.orphan));
t('兩種位置的儲存格註解（Excel、openpyxl）都讀到', x && x.comments.length === 2, JSON.stringify(x && x.comments));
const sx = core.scanFile(xl);
t('xlsx 擋異動紀錄用語（rich text 拆開的「本次查核」）', sx.bad.some((b) => b.includes('本次查核')), JSON.stringify(sx.bad));
t('xlsx 擋深度隱藏工作表裡的 AI 工具名稱', sx.bad.some((b) => b.includes('Codex')), JSON.stringify(sx.bad));
t('隱藏工作表列名稱提醒（含深度隱藏）', sx.notes.some((n) => n.includes('內部試算') && n.includes('草稿') && n.includes('深度隱藏')), JSON.stringify(sx.notes));
t('儲存格註解的推導痕跡也提醒', sx.notes.some((n) => n.includes('原價')) && sx.notes.some((n) => n.includes('2 則儲存格註解')), JSON.stringify(sx.notes));
t('不是 zip 的 xlsx → 丟 ReadError', (() => { const j = path.join(tmp, 'junk.xlsx'); fs.writeFileSync(j, 'x');
  try { core.scanFile(j); return false; } catch (e) { return e instanceof core.ReadError; } })(), '');
// 第二張工作表的檔案不在：只掃第一張就放行，第二張裡有什麼都看不到
const lostSheet = zip(path.join(tmp, 'lost.xlsx'), {
  'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>' +
    '<sheet name="估算" sheetId="1" r:id="rId1"/><sheet name="內部試算" sheetId="2" r:id="rId2"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/>' +
    '<Relationship Id="rId2" Target="worksheets/sheet2.xml"/></Relationships>',
  'xl/worksheets/sheet1.xml': '<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>正常內容</t></is></c></row></sheetData></worksheet>',
});
let lostErr = null;
try { core.scanFile(lostSheet); } catch (e) { lostErr = e; }
t('有工作表讀不到 → 丟 ReadError 並寫出哪一張（不只掃其餘工作表就放行）',
  lostErr instanceof core.ReadError && lostErr.message.includes('內部試算'), String(lostErr && lostErr.message));
// 把指定 entry 在中央目錄與本地標頭的壓縮方式改成不存在的 99：解壓必定失敗
function breakEntry(file, entry) {
  const b = fs.readFileSync(file);
  const name = Buffer.from(entry);
  for (let i = 0; i + 46 < b.length; i++) {
    if (b.readUInt32LE(i) === 0x02014b50 && b.subarray(i + 46, i + 46 + name.length).equals(name)) { b.writeUInt16LE(99, i + 10); b.writeUInt16LE(99, b.readUInt32LE(i + 42) + 8); }
  }
  fs.writeFileSync(file, b);
  return file;
}
const xlParts = (extra) => Object.assign({
  'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="估算" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/worksheets/sheet1.xml': '<worksheet><sheetData><row><c r="A1" t="s"><v>0</v></c><c r="B1" t="inlineStr"><is><t>正常內容</t></is></c></row></sheetData></worksheet>',
}, extra);
const readErr = (f) => { try { core.scanFile(f); return null; } catch (e) { return e; } };
let e1 = readErr(zip(path.join(tmp, 'noss.xlsx'), xlParts({})));
t('儲存格引用共用字串、但共用字串檔不在 → ReadError（引用的文字不能靜默消失）',
  e1 instanceof core.ReadError && e1.message.includes('共用字串'), String(e1 && e1.message));
e1 = readErr(breakEntry(zip(path.join(tmp, 'badss.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>本段由 Codex 產生</t></si></sst>' })), 'xl/sharedStrings.xml'));
t('共用字串檔解壓失敗 → ReadError', e1 instanceof core.ReadError && e1.message.includes('sharedStrings'), String(e1 && e1.message));
e1 = readErr(breakEntry(zip(path.join(tmp, 'badcm.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/comments1.xml': '<comments><commentList><comment ref="A1"><text><t>原價 15 人天</t></text></comment></commentList></comments>' })), 'xl/comments1.xml'));
t('儲存格註解解壓失敗 → ReadError', e1 instanceof core.ReadError && e1.message.includes('comments1'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'emptysheet.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>', 'xl/worksheets/sheet1.xml': '' })));
t('工作表檔是空的（不是工作表 XML）→ ReadError', e1 instanceof core.ReadError && e1.message.includes('估算'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'relcm.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/_rels/sheet1.xml.rels': '<Relationships><Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/></Relationships>' })));
t('工作表關聯到的註解檔不在 zip 裡 → ReadError', e1 instanceof core.ReadError && e1.message.includes('xl/comments1.xml'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'relcm-ok.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/_rels/sheet1.xml.rels': '<Relationships><Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/></Relationships>',
  'xl/comments1.xml': '<comments><commentList><comment ref="A1"><text><t>比照去年</t></text></comment></commentList></comments>' })));
t('關聯的註解檔在 → 正常讀（不誤報讀不到）', e1 === null, String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'trunc.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/sheet1.xml': '<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>本段由 Codex' })));
t('工作表檔被截斷（有開頭沒有結束標籤）→ ReadError', e1 instanceof core.ReadError && e1.message.includes('估算'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'wrongroot.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/sheet1.xml': '<foo><worksheet/></foo>' })));
t('根元素不是工作表（<foo><worksheet/></foo>）→ ReadError', e1 instanceof core.ReadError && e1.message.includes('估算'), String(e1 && e1.message));
// 讀不到時當成沒擋下（該項 FAIL），不讓整支測試中斷
const scanOrEmpty = (f) => { try { return core.scanFile(f); } catch (e) { return { bad: [`讀不到：${e.message}`] }; } };
const pre = scanOrEmpty(zip(path.join(tmp, 'prefix.xlsx'), {
  'xl/workbook.xml': '<?xml version="1.0"?><x:workbook xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><x:sheets><x:sheet name="估算" sheetId="1" r:id="rId1"/></x:sheets></x:workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/worksheets/sheet1.xml': '<x:worksheet xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><x:sheetData><x:row><x:c r="A1" t="inlineStr"><x:is><x:t>本段由 Codex 產生</x:t></x:is></x:c></x:row></x:sheetData></x:worksheet>',
}));
t('標籤帶命名空間前綴（<x:row>、<x:t>）的工作表照樣讀到內容並擋下', pre.bad.some((b) => b.includes('Codex')), JSON.stringify(pre.bad));
const notes = scanOrEmpty(zip(path.join(tmp, 'notes.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/_rels/sheet1.xml.rels': '<Relationships><Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../notes.xml"/></Relationships>',
  'xl/notes.xml': '<comments><commentList><comment ref="A1"><text><t>本段由 Codex 產生</t></text></comment></commentList></comments>' })));
t('工作表關聯到檔名不是 comments 的註解檔（../notes.xml）也讀到並擋下', notes.bad.some((b) => b.includes('Codex')), JSON.stringify(notes.bad));
const CODEX_ROW = '<sheetData><row><c r="A1" t="inlineStr"><is><t>本段由 Codex 產生</t></is></c></row></sheetData>';
const okSheet = (sheet, file) => scanOrEmpty(zip(path.join(tmp, file), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>', 'xl/worksheets/sheet1.xml': sheet })));
let r7 = okSheet(`<worksheet>${CODEX_ROW}</worksheet><!-- saved --><?pi x?>`, 'tailnode.xlsx');
t('根元素後面有 XML 註解、處理指令仍是合格檔，照樣讀到並擋下', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));
r7 = okSheet(`<worksheet note="a/>b" alt='x>y'>${CODEX_ROW}</worksheet>`, 'attrslash.xlsx');
t('屬性值裡有 /> 或 >（引號內）不會被當成標籤結束，照樣讀到並擋下', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));
r7 = okSheet('<worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t><![CDATA[本段由 Codex 產生 <x:y>]]></t></is></c></row></sheetData></worksheet>', 'cdata.xlsx');
t('CDATA 包住的儲存格文字照樣讀到並擋下', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));

// ---- XML 交給 Python 標準庫解析：命名空間前綴不限英文、深巢狀不當掉、索引只收純數字 ----
r7 = okSheet('<中:worksheet xmlns:中="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><中:sheetData><中:row><中:c r="A1" t="inlineStr"><中:is><中:t>本段由 Codex 產生</中:t></中:is></中:c></中:row></中:sheetData></中:worksheet>', 'cjkprefix.xlsx');
t('中文命名空間前綴（<中:row>）的工作表照樣讀到並擋下', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));
{
  // 內容太長不能當命令列參數傳給 zip()：先寫成檔，再由 Python 換進 zip
  const deepXml = path.join(tmp, 'deep-sheet.xml');
  fs.writeFileSync(deepXml, `<worksheet><sheetData>${'<x>'.repeat(20000)}${'</x>'.repeat(20000)}<row><c r="A1" t="inlineStr"><is><t>深處</t></is></c></row></sheetData></worksheet>`);
  const deep = zip(path.join(tmp, 'deep.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>' }));
  py(`
import sys, zipfile, shutil
src, dst = sys.argv[1], sys.argv[1] + '.tmp'
x = open(sys.argv[2], encoding='utf-8').read()
with zipfile.ZipFile(src) as a, zipfile.ZipFile(dst, 'w') as b:
    for n in a.namelist(): b.writestr(n, x if n == 'xl/worksheets/sheet1.xml' else a.read(n))
shutil.move(dst, src)
`, deep, deepXml);
  e1 = readErr(deep);
}
t('兩萬層巢狀的工作表不會讓程式當掉（照常讀完）', e1 === null, String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'blankidx.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>第一筆</t></si></sst>',
  'xl/worksheets/sheet1.xml': '<worksheet><sheetData><row><c r="A1" t="s"><v> </v></c><c r="B1" t="s"><v>0x0</v></c></row></sheetData></worksheet>' })));
t('共用字串索引是空白或 0x0 → 算引用不存在、ReadError（不可讀成第 1 筆）', e1 instanceof core.ReadError && e1.message.includes('2 個儲存格'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'hugeidx.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>第一筆</t></si></sst>',
  'xl/worksheets/sheet1.xml': `<worksheet><sheetData><row><c r="A1" t="s"><v>${'9'.repeat(5000)}</v></c></row></sheetData></worksheet>` })));
{
  let rx = null, ex = null;
  try { rx = core.readXlsx(zip(path.join(tmp, 'zeroidx.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>第一筆</t></si><si><t>第二筆</t></si></sst>',
    'xl/worksheets/sheet1.xml': `<worksheet><sheetData><row><c r="A1" t="s"><v>0000000000</v></c><c r="B1" t="s"><v>${'0'.repeat(5000)}1</v></c></row></sheetData></worksheet>` }))); } catch (x) { ex = x; }
  const row = rx && rx.sheets[0] && rx.sheets[0].rows[0];
  t('共用字串索引帶前導零（0000000000、5000 個 0 接 1）仍是合法索引，讀成第 1、2 筆', !ex && row && row.includes('第一筆') && row.includes('第二筆'), String(ex && ex.message) + ' ' + JSON.stringify(rx && rx.sheets));
}
t('共用字串索引是 5000 位數字 → 算引用不存在（資料問題），不是 Python 沒跑成',
  e1 instanceof core.ReadError && !(e1 instanceof core.PythonFailed) && e1.message.includes('1 個儲存格'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'dtd.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/sheet1.xml': '<!DOCTYPE worksheet [<!ENTITY a "Codex">]><worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>&a;</t></is></c></row></sheetData></worksheet>' })));
t('含 DTD 宣告的工作表 → ReadError（不展開自訂實體）', e1 instanceof core.ReadError && e1.message.includes('估算'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'norel.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/workbook.xml': '<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="估算" sheetId="1" r:id="rId1"/><sheet name="附表" sheetId="2" r:id="rId9"/></sheets></workbook>' })));
t('工作表的關聯 id 在關聯檔裡找不到 → ReadError 並寫出哪一張', e1 instanceof core.ReadError && e1.message.includes('附表'), String(e1 && e1.message));
e1 = readErr(zip(path.join(tmp, 'badsheetrels.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/worksheets/_rels/sheet1.xml.rels': '<Relationships><Relationship Id="rId1" Target="../comments1.xml"' })));
t('工作表的關聯檔格式錯 → ReadError（關聯到的註解有沒有、在哪都不知道）', e1 instanceof core.ReadError && e1.message.includes('關聯檔'), String(e1 && e1.message));
r7 = scanOrEmpty(zip(path.join(tmp, 'threaded.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/threadedComments/threadedComment1.xml': '<ThreadedComments xmlns="http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments"><threadedComment ref="A1" id="{1}"><text>這段請 Codex 再算一次</text></threadedComment></ThreadedComments>' })));
t('新式討論串（threadedComments）的內容照樣讀到並擋下', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));
{
  // UTF-16 編碼的工作表含 DTD：位元組裡沒有 ASCII 的 <!DOCTYPE，要由解析器判斷
  const f16 = zip(path.join(tmp, 'utf16dtd.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>' }));
  py(`
import sys, zipfile, shutil
src, dst = sys.argv[1], sys.argv[1] + '.tmp'
x = '<?xml version="1.0" encoding="UTF-16"?><!DOCTYPE worksheet [<!ENTITY a "Codex">]><worksheet><sheetData><row><c r="A1" t="inlineStr"><is><t>&a;</t></is></c></row></sheetData></worksheet>'
with zipfile.ZipFile(src) as a, zipfile.ZipFile(dst, 'w') as b:
    for n in a.namelist(): b.writestr(n, x.encode('utf-16') if n == 'xl/worksheets/sheet1.xml' else a.read(n))
shutil.move(dst, src)
`, f16);
  e1 = readErr(f16);
  t('UTF-16 編碼的工作表含 DTD 宣告 → ReadError（不展開自訂實體）', e1 instanceof core.ReadError && e1.message.includes('估算'), String(e1 && e1.message));
}
const metaOf = (core_xml, file) => core.checkMetadata(zip(path.join(tmp, file), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>', 'docProps/core.xml': core_xml })));
let mm = metaOf('<cp:coreProperties xmlns:cp="x" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>估算</dc:title><dc:creator><![CDATA[Codex]]></dc:creator></cp:coreProperties>', 'meta-cdata.xlsx');
t('文件屬性：CDATA 包住的作者照樣讀到並擋下，同一句只報一次', mm.bad.filter((b) => b.includes('Codex')).length === 1, JSON.stringify(mm.bad));
mm = metaOf('<cp:coreProperties xmlns:cp="x" xmlns:d="http://purl.org/dc/elements/1.1/"><d:title>估算</d:title><d:creator>Codex</d:creator></cp:coreProperties>', 'meta-prefix.xlsx');
t('文件屬性：前綴不是 dc:（<d:creator>）照樣讀到並擋下', mm.bad.some((b) => b.includes('Codex')), JSON.stringify(mm.bad));
{
  let e = null;
  try { metaOf('<cp:coreProperties xmlns:cp="x" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>估算</dc:title><dc:creator>王小明</dc:creator><dc:creator>Codex</dc:creator></cp:coreProperties>', 'meta-dup.xlsx'); } catch (x) { e = x; }
  t('文件屬性：同一欄位出現兩次 → ReadError（只看其中一個不算檢查過）', e instanceof core.ReadError && e.message.includes('重複'), String(e && e.message));
  const bad = [];
  for (const [name, xml] of [['meta-root-empty.xlsx', '<foo/>'], ['meta-root-other.xlsx', '<foo xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:creator>王小明</dc:creator></foo>']]) {
    let x = null;
    try { metaOf(xml, name); } catch (y) { x = y; }
    if (!(x instanceof core.ReadError && x.message.includes('根元素'))) bad.push(name + '：' + String(x && x.message));
  }
  t('文件屬性：core.xml 根元素不是 coreProperties → ReadError（不當成空白屬性）', bad.length === 0, bad.join('；'));
}

// ---- 沒裝 Python：不擋，但一定要說缺什麼、怎麼裝（DR_PYTHON 指到不存在的執行檔來模擬）----
{
  const NOPY = path.join(tmp, 'no-such-python.exe');
  process.env.DR_PYTHON = NOPY;
  let e = null;
  try { core.readXlsx(xl); } catch (x) { e = x; }
  t('沒有 Python：讀 xlsx 丟 NeedsPython，訊息寫明要安裝 Python', e instanceof core.NeedsPython && /安裝 Python 3/.test(e.message), String(e && e.message));
  e = null;
  try { core.checkMetadata(pydocx); } catch (x) { e = x; }
  t('沒有 Python：讀 docx 文件屬性也丟 NeedsPython', e instanceof core.NeedsPython, String(e && e.message));
  delete process.env.DR_PYTHON;
  const env = { ...process.env, DR_PYTHON: NOPY };
  let c = spawnSync(process.execPath, [CHECK, xl, '--no-visual'], { encoding: 'utf8', env });
  t('沒有 Python 時檢查 xlsx：不 exit 2、列進「這次沒檢查到的」並寫明怎麼裝，硬缺陷那行講明內容沒讀（不打勾）',
    c.status === 0 && /這次沒檢查到的[\s\S]*文件內容：[\s\S]*安裝 Python 3/.test(c.stdout) && c.stdout.includes('文件內容沒有讀取') && !c.stdout.includes('✓ 硬缺陷'),
    `exit=${c.status} ${c.stdout}`);
  c = spawnSync(process.execPath, [CHECK, pydocx, '--no-visual'], { encoding: 'utf8', env });
  t('沒有 Python 時檢查 docx：內文照掃，文件屬性記成提醒並寫明怎麼裝、不 exit 2', c.status !== 2 && /文件屬性未檢查[\s\S]*安裝 Python 3/.test(c.stdout), `exit=${c.status} ${c.stdout}`);
  c = spawnSync(process.execPath, [CHECK, xl, '--no-visual', '--json'], { encoding: 'utf8', env });
  let cj = null; try { cj = JSON.parse(c.stdout); } catch (_) { /* 下面判斷 */ }
  t('沒有 Python 時 --json：exit 0（不擋）但 pass=false（不讓只看 pass 的程式當成通過）', c.status === 0 && cj && cj.pass === false, `exit=${c.status} ${c.stdout.slice(0, 200)}`);
  const prevTxt = path.join(tmp, 'prev-clauses.txt'), mailTxt = path.join(tmp, 'mail.txt');
  const LF = String.fromCharCode(10);
  fs.writeFileSync(prevTxt, ['付款：驗收後 30 日內付款', '保固一年', '總價 NT$250,000 元整', ''].join(LF));
  fs.writeFileSync(mailTxt, ['Date: Tue, 8 Sep 2026 10:00:00 +0800', '', '已確認', ''].join(LF));
  c = spawnSync(process.execPath, [CHECK, xl, '--no-visual', '--prev', prevTxt, '--thread', mailTxt], { encoding: 'utf8', env });
  t('沒有 Python、內容沒讀時不拿空內容比對：不報條款消失，來信對照與條款比對列進「這次沒檢查到的」',
    c.status === 0 && !c.stdout.includes('新版找不到') && /客戶來信對照：文件內容沒有讀取/.test(c.stdout) && /合約條款比對：文件內容沒有讀取/.test(c.stdout),
    `exit=${c.status} ${c.stdout}`);
  c = spawnSync(process.execPath, [CHECK, xl, '--no-visual', '--thread', mailTxt, '--json'], { encoding: 'utf8', env });
  cj = null; try { cj = JSON.parse(c.stdout); } catch (_) { /* 下面判斷 */ }
  t('沒有 Python 時 --json 的 thread 為 null（沒對照就不輸出對照結果）', cj && cj.thread === null, c.stdout.slice(0, 300));
  c = spawnSync(process.execPath, [CHECK, pydocx, '--no-visual', '--json'], { encoding: 'utf8', env });
  cj = null; try { cj = JSON.parse(c.stdout); } catch (_) { /* 下面判斷 */ }
  t('沒有 Python 時 docx 內文照掃、只有文件屬性沒查 → pass 仍是 false（exit 不變）', c.status !== 2 && cj && cj.pass === false, `exit=${c.status} ${c.stdout.slice(0, 200)}`);
  const mdDoc = path.join(tmp, 'plain.md');
  fs.writeFileSync(mdDoc, ['# 報價', '', '付款：驗收後 30 日', ''].join(String.fromCharCode(10)));
  c = spawnSync(process.execPath, [CHECK, mdDoc, '--prev', xl, '--json'], { encoding: 'utf8', env });
  cj = null; try { cj = JSON.parse(c.stdout); } catch (_) { /* 下面判斷 */ }
  t('沒有 Python 時 --prev 給 xlsx 讀不了 → pass 是 false、列進「這次沒檢查到的」', c.status === 0 && cj && cj.pass === false && cj.unchecked.some((u) => u.startsWith('合約條款比對：')), `exit=${c.status} ${c.stdout.slice(0, 300)}`);
  c = spawnSync(process.execPath, [CHECK, pydocx, '--no-visual', '--prev', xl], { encoding: 'utf8', env });
  t('沒有 Python 時 --prev 給 xlsx：條款比對列進「這次沒檢查到的」，不 exit 2', c.status !== 2 && /這次沒檢查到的[\s\S]*合約條款比對：讀不了上一版/.test(c.stdout), `exit=${c.status} ${c.stdout}`);
}

// ---- check_doc.js：只給檔名找得到 xlsx ----
let r = check(['人天估算', '--root', tmp]);
t('只給檔名（省略副檔名）找得到 xlsx 並掃描', r.code === 1 && r.out.includes('人天估算.xlsx') && r.out.includes('格式：xlsx'), r.out.slice(0, 300));
r = check(['人天估算.xlsx', '--root', tmp]);
t('給完整檔名也找得到', r.out.includes('格式：xlsx'), r.out.slice(0, 200));

// ---- check_doc.js：來信對照與條款比對 ----
const v1 = zip(path.join(tmp, '報價單v1.docx'), {
  'word/document.xml': DOC(['報價單', '一、付款條件：驗收後 30 日內付款，票期 60 天。', '二、總價 NT$250,000 元整（未稅）。', '三、保固一年。', '四、報表數量待客戶確認。']),
  'docProps/core.xml': CORE('<dc:title>報價單</dc:title><dc:creator>王小明</dc:creator>'),
});
const v2 = zip(path.join(tmp, '報價單v2.docx'), {
  'word/document.xml': DOC(['報價單', '一、付款條件：驗收後 30 日內付款。', '二、總價 NT$280,000 元整（未稅）。', '三、報表數量待客戶確認。', '四、上線日 TBD。']),
  'docProps/core.xml': CORE('<dc:title>報價單</dc:title><dc:creator>王小明</dc:creator>'),
});
const thread = path.join(tmp, 'thread.txt');
fs.writeFileSync(thread, 'From: 客戶\nDate: Tue, 8 Sep 2026 10:00:00 +0800\n\n報表數量確定為 12 張。\n\n> 2026/9/1 我方來信\n');

r = check([v2]);
t('沒給 --thread／--prev：列在「這次沒檢查到的」、exit 0（不算缺陷也不算通過）',
  r.code === 0 && r.out.includes('這次沒檢查到的 2 項') && r.out.includes('2 條待確認沒有對照') && r.out.includes('沒給 --prev'), r.out);
r = check([v2, '--thread', thread, '--prev', v1]);
t('--thread：列出兩條待確認（第幾段＋原句）與信件最新日期 2026-09-08',
  r.out.includes('2 條待確認') && r.out.includes('2026-09-08') && r.out.includes('第 4 段「三、報表數量待客戶確認。」') && r.out.includes('TBD'), r.out);
t('--prev：票期整段消失、保固消失 → 提醒需確認是否刻意刪除',
  r.out.includes('「票期」舊版有、新版找不到') && r.out.includes('「保固」舊版有、新版找不到'), r.out);
t('--prev：金額數字變動附舊值／新值', r.out.includes('「金額」數字變動：舊值 250000 → 新值 280000'), r.out);
t('來信對照與條款比對都只是提醒：exit 0、沒有「這次沒檢查到的」', r.code === 0 && !r.out.includes('這次沒檢查到的'), r.out);
r = check([v2, '--thread', thread, '--json']);
let j = null;
try { j = JSON.parse(r.out); } catch (_) { /* 下面判 */ }
t('--json 帶 metadata、thread（latest＋pending）、unchecked 欄位',
  j && j.metadata && j.metadata.title === '報價單' && j.thread.latest === '2026-09-08' && j.thread.pending.length === 2 && j.unchecked.length === 1, r.out.slice(0, 300));
t('--thread 後面接旗標 → exit 2', check([v2, '--thread', '--json']).code === 2, '');
t('--prev 指到不存在的檔 → exit 2', check([v2, '--prev', path.join(tmp, 'nope.docx')]).code === 2, '');

// ---- 日報、確認清單這類 md：寄送與轉檔也呼叫這支並照印輸出，不可出現「不算通過」 ----
const md = path.join(tmp, '日報.md');
fs.writeFileSync(md, '# 工作日報\n\n今天完成登入頁的欄位調整，驗收時間待客戶確認。\n\n付款流程 TBD。\n');
r = check([md]);
t('md 有待確認、有條款字眼 → 仍不列「這次沒檢查到的」、註明文件屬性不適用',
  r.code === 0 && !r.out.includes('這次沒檢查到的') && r.out.includes('沒有文件屬性'), r.out);
const pend = core.pendingItems(core.scanFile(md).text);
t('段落編號不算空行（md 第 2、3 段，不是第 3、5 行）', JSON.stringify(pend.map((p) => p.para)) === '[2,3]', JSON.stringify(pend));

// ---- 機密不可從屬性訊息與 --json 漏出 ----
const SECRET = 'sk-' + 'A'.repeat(24);
const leak = zip(path.join(tmp, '說明.docx'), {
  'word/document.xml': DOC(['正文']),
  'docProps/core.xml': CORE(`<dc:title>說明</dc:title><dc:description>Claude 用 ${SECRET}</dc:description>`),
});
m = core.checkMetadata(leak);
t('屬性同時含 AI 名稱與密鑰 → 兩項都擋，但訊息裡沒有密鑰原文',
  m.bad.length === 2 && m.bad.every((b) => !b.includes(SECRET)), JSON.stringify(m.bad));
r = check([leak, '--json']);
t('--json 的 metadata 欄位也遮蔽密鑰', r.out.includes('"metadata"') && !r.out.includes(SECRET), r.out.slice(0, 400));
r = check([leak]);
t('文字輸出表頭與訊息都沒有密鑰原文', !r.out.includes(SECRET), r.out);

// ---- 屬性檔解不開＝讀不到，不可當成檢查過 ----
const broken = path.join(tmp, '壞屬性.docx');
py(`
import sys, zipfile
with zipfile.ZipFile(sys.argv[1], 'w') as z:
    z.writestr('word/document.xml', '<w:document xmlns:w="w"><w:body><w:p><w:r><w:t>正文</w:t></w:r></w:p></w:body></w:document>')
    z.writestr(zipfile.ZipInfo('docProps/core.xml'), b'not deflate data at all')
`, broken);
// core.xml 以不壓縮（stored）寫入，再把中央目錄與本地標頭的壓縮方式欄位改成 deflate：內容不是 deflate 資料，解壓必定失敗
{
  const b = fs.readFileSync(broken);
  const name = Buffer.from('docProps/core.xml');
  for (let i = 0; i + 46 < b.length; i++) {
    if (b.readUInt32LE(i) === 0x02014b50 && b.subarray(i + 46, i + 46 + name.length).equals(name)) { b.writeUInt16LE(8, i + 10); b.writeUInt16LE(8, b.readUInt32LE(i + 42) + 8); }
  }
  fs.writeFileSync(broken, b);
}
let threw = false;
try { core.checkMetadata(broken); } catch (e) { threw = e instanceof core.ReadError; }
t('docProps 解不開 → 丟 ReadError（不當成空白屬性）', threw, '');
r = check([broken]);
t('check_doc：屬性讀不到記成提醒「文件屬性未檢查」、不 exit 2', r.code !== 2 && /提醒[\s\S]*文件屬性未檢查/.test(r.out), r.out);

// ---- 信件日期：有標頭只看標頭；沒標頭時排除未來日期 ----
t('有 Date 標頭時，內文的交期日期不算來信日期',
  core.latestMailDate('Date: Tue, 8 Sep 2026 10:00:00 +0800\n\n上次約定 2026/9/20 交貨').date === '2026-09-08', '');
t('中文日期標頭（寄件日期：2026年9月8日）也認得，內文日期不算',
  core.latestMailDate('寄件日期：2026年9月8日\n\n上次約定 2026/9/20 交貨').date === '2026-09-08', JSON.stringify(core.latestMailDate('寄件日期：2026年9月8日\n\n上次約定 2026/9/20 交貨')));
const dec = core.compareClauses(['3.5 付款：驗收後 30 日'], ['4.5 付款：驗收後 30 日']);
t('句首小數（3.5）不當項次編號，3.5 → 4.5 會報', dec.some((n) => n.includes('3.5') && n.includes('4.5')), JSON.stringify(dec));
const mixed = 'Date: Tue, 8 Sep 2026 10:00:00 +0800\n\n第一封\n\n寄件日期: 2026/9/10 上午 10:00\n\n第二封';
t('英文與中文標頭混合（Outlook 轉寄串）→ 兩種都算，取較新的 2026-09-10', core.latestMailDate(mixed).date === '2026-09-10', JSON.stringify(core.latestMailDate(mixed)));
t('沒有標頭時用內文日期，但排除晚於明天的日期',
  core.latestMailDate('9/1 來信\n2026/9/1 確認\n交期 2099/3/1').date === '2026-09-01', JSON.stringify(core.latestMailDate('2026/9/1 確認\n交期 2099/3/1')));
const emptyHdr = core.latestMailDate('Date:\n\n交期 2099/3/1');
t('空白的 Date: 標頭不會跨行抓到下一段內文的交期', emptyHdr === null, JSON.stringify(emptyHdr));
const noYear = [core.latestMailDate('Date: 3'), core.latestMailDate('日期: 9/8')];
t('標頭沒寫年份（Date: 3、日期: 9/8）不會被補成 2001 年', noYear.every((x) => x === null), JSON.stringify(noYear));
const feb31 = [core.latestMailDate('日期：2026年2月31日'), core.latestMailDate('Date: Tue, 31 Feb 2026 10:00:00 +0800'), core.latestMailDate('2026/2/31 來信')];
t('不存在的日期（2 月 31 日）不會被進位成 3 月 3 日——中文標頭、英文標頭、內文三種都一樣', feb31.every((x) => x === null), JSON.stringify(feb31));
const outlook = core.latestMailDate('Sent: Tuesday, September 8, 2026 10:00 AM\n\n內文');
t('Outlook 的 Sent: 標頭（月名 日, 年）也認得', outlook && outlook.date === '2026-09-08', JSON.stringify(outlook));
const y1999 = core.latestMailDate('Date: Fri, 31 Dec 1999 10:00:00 +0800');
t('19xx 年的標頭也認得（Date: Fri, 31 Dec 1999）', y1999 && y1999.date === '1999-12-31', JSON.stringify(y1999));
const mkt = core.latestMailDate('Sent: Marketing 8, 2026');
t('不是月名的英文字（Marketing 8, 2026）不會被當成 3 月 8 日', mkt === null, JSON.stringify(mkt));
const paren = [core.compareClauses(['(1)30 日付款'], ['(2)30 日付款']), core.compareClauses(['1、30 日付款'], ['2、30 日付款'])];
t('括號與頓號項次後面直接接數字，項次照樣去掉、不報變動', paren.every((x) => x.length === 0), JSON.stringify(paren));

// ---- 條款數字：項次編號不算、重複數字少一次也算 ----
let cn = core.compareClauses(['1. 付款：驗收後 30 日', '2. 驗收：上線後 10 日'], ['1. 驗收：上線後 10 日', '2. 付款：驗收後 30 日']);
t('只是項次順序對調 → 不報數字變動', cn.length === 0, JSON.stringify(cn));
cn = core.compareClauses(['付款：分 2 期，每期 50 萬，尾款 50 萬'], ['付款：分 2 期，每期 50 萬']);
t('同一個數字少了一次（50 出現兩次變一次）→ 報數字變動', cn.some((n) => n.includes('付款條件') && n.includes('50')), JSON.stringify(cn));
cn = core.compareClauses(['付款：洽承辦 0912-345-678 確認'], ['（本版改由合約另訂）']);
t('條款消失時印出的舊版原句先遮蔽電話等個資', cn.length === 1 && !cn[0].includes('0912-345-678') && cn[0].includes('已遮蔽'), JSON.stringify(cn));
const odd = core.latestMailDate('文件編號 1131-05-06');
t('19xx／20xx 以外的四位數（文件編號 1131-05-06）不當成年份', odd === null, JSON.stringify(odd));
r7 = scanOrEmpty(zip(path.join(tmp, 'sheetname.xlsx'), xlParts({ 'xl/sharedStrings.xml': '<sst><si><t>報表</t></si></sst>',
  'xl/workbook.xml': '<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Codex 試算" sheetId="1" r:id="rId1"/></sheets></workbook>' })));
t('工作表名稱也掃（分頁上的 AI 工具名稱照樣擋下）', r7.bad.some((b) => b.includes('Codex')), JSON.stringify(r7.bad));

// ---- xlsx：數值儲存格與條款同列才比得到；表格代碼不擋 ----
const xlq = (file, amount, code) => zip(file, {
  'xl/workbook.xml': '<?xml version="1.0"?><workbook xmlns:r="r"><sheets><sheet name="報價" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels': '<?xml version="1.0"?><Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/sharedStrings.xml': `<sst><si><t>總價</t></si><si><t>${code}</t></si></sst>`,
  'xl/worksheets/sheet1.xml': `<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1"><v>${amount}</v></c></row>` +
    '<row r="2"><c r="A2" t="s"><v>1</v></c></row></sheetData></worksheet>',
  'docProps/core.xml': CORE('<dc:title>報價</dc:title><dc:creator>王小明</dc:creator>'),
});
const q1 = xlq(path.join(tmp, '報價1.xlsx'), 250000, '規格 V2'), q2 = xlq(path.join(tmp, '報價2.xlsx'), 280000, '規格 V2');
r = check([q2, '--prev', q1]);
t('xlsx：金額在數值儲存格、「總價」在同列 → --prev 報 250000 → 280000', r.out.includes('「金額」數字變動：舊值 250000 → 新值 280000'), r.out);
const sq = core.scanFile(q2);
t('xlsx：資料格的「V2」不算未定義代號硬缺陷，改為提醒', !sq.bad.some((b) => b.startsWith('鐵則4')) && sq.notes.some((n) => n.startsWith('鐵則4')), JSON.stringify(sq));

// ---- Stop hook：交付訊息提到的 xlsx 也會掃（格式清單取自 core 的 SUPPORTED）；文件屬性不在 Stop hook 範圍 ----
{
  const HOOK = path.join(ROOT, 'hooks', 'doc-readability-gate.js');
  const lines = [
    { type: 'user', promptId: 'p1', message: { role: 'user', content: '幫我交付' } },
    { type: 'assistant', message: { content: [{ type: 'tool_use', id: 't1', name: 'Skill', input: { skill: 'deliver-report:deliver-report' } }] } },
    { type: 'user', promptId: 'p1', toolUseResult: { success: true }, message: { role: 'user', content: [] } },
  ];
  const run = (text, env) => {
    const tp = path.join(tmp, 'tr.jsonl');
    fs.writeFileSync(tp, [...lines, { type: 'assistant', message: { content: [{ type: 'text', text }] } }].map((o) => JSON.stringify(o)).join('\n') + '\n');
    const h = spawnSync(process.execPath, [HOOK], { input: JSON.stringify({ cwd: tmp, transcript_path: tp, stop_hook_active: false }), encoding: 'utf8', timeout: 180000, env: env || process.env });
    try { const o = JSON.parse(h.stdout); return { d: o.decision || 'warn', t: o.reason || o.systemMessage || '' }; } catch (_) { return { d: 'allow', t: '' }; }
  };
  let h = run('估算表在 `人天估算.xlsx`，請過目。');
  t('Stop hook：交付訊息提到的 xlsx 被掃，內容缺陷會擋', h.d === 'block' && h.t.includes('人天估算.xlsx'), h.d + ' ' + h.t);
  h = run('估算表在 `opx.xlsx`，請過目。');
  t('Stop hook 不跑文件屬性檢查（openpyxl 預設作者不會在收尾時擋）', h.d === 'allow', h.d + ' ' + h.t);
  h = run('估算表在 `人天估算.xlsx`，請過目。', { ...process.env, DR_PYTHON: path.join(tmp, 'no-such-python.exe') });
  t('Stop hook：沒有 Python 時不擋，但提醒哪份檔沒檢查、要裝 Python（不靜默放行）', h.d === 'warn' && h.t.includes('人天估算.xlsx') && /安裝 Python 3/.test(h.t), h.d + ' ' + h.t);

  // Python 本身沒跑成（這裡用啟動設定讓 office_xml.py 那次執行異常結束；探測 Python 照常成功）
  const crashDir = path.join(tmp, 'crash');
  fs.mkdirSync(crashDir, { recursive: true });
  fs.writeFileSync(path.join(crashDir, 'sitecustomize.py'),
    ['import sys', 'if any("office_xml" in a for a in sys.argv):', '    raise SystemExit(3)', ''].join(String.fromCharCode(10)));
  const crashEnv = { ...process.env, PYTHONPATH: crashDir };
  h = run('估算表在 `人天估算.xlsx`，請過目。', crashEnv);
  t('Stop hook：Python 異常結束而沒檢查的檔不擋，但列出檔名提醒（不靜默放行）', h.d === 'warn' && h.t.includes('人天估算.xlsx') && h.t.includes('沒跑成'), h.d + ' ' + h.t);
  const cc = spawnSync(process.execPath, [CHECK, pydocx, '--no-visual', '--json'], { encoding: 'utf8', env: crashEnv });
  t('讀文件屬性時 Python 異常結束 → exit 2、寫明讀取失敗（不降成「文件屬性未檢查」提醒）',
    cc.status === 2 && cc.stdout.includes('文件屬性讀取失敗') && !cc.stdout.includes('文件屬性未檢查'), `exit=${cc.status} ${cc.stdout.slice(0, 300)}`);
  // office_xml.py 正常結束卻什麼都沒印（輸出不完整）同樣是 Python 沒跑成
  const silentDir = path.join(tmp, 'silent');
  fs.mkdirSync(silentDir, { recursive: true });
  fs.writeFileSync(path.join(silentDir, 'sitecustomize.py'),
    ['import sys, os', 'if any("office_xml" in a for a in sys.argv):', '    os._exit(0)', ''].join(String.fromCharCode(10)));
  const cs = spawnSync(process.execPath, [CHECK, pydocx, '--no-visual'], { encoding: 'utf8', env: { ...process.env, PYTHONPATH: silentDir } });
  t('office_xml.py 沒有回傳結果 → 文件屬性 exit 2（不降成提醒）', cs.status === 2 && cs.stdout.includes('沒有回傳結果'), `exit=${cs.status} ${cs.stdout.slice(0, 300)}`);
}

fs.rmSync(tmp, { recursive: true, force: true });
console.log(`\n  → ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
